### ISSUE TITLE
Leave Edge Installed?

### ISSUE THREAD

**Issue by Brodieman** [ntdevlabs/tiny11builder#102]
Is there a good way to leave Edge installed?  I may be in the minority of IT professionals but I like Edge.  I'll dig trough the batch looking for lines to remove but I don't want to break anything else.

**Comment by Brodieman** [comment]
I removed these lines, will that do it and leave the rest of the script fine?

`echo Removing Edge:`
`rd "C:\scratchdir\Program Files (x86)\Microsoft\Edge" /s /q`
`rd "C:\scratchdir\Program Files (x86)\Microsoft\EdgeUpdate" /s /q`

**Comment by RaySlash** [comment]
@Brodieman You should be fine with just that. Everything happens inside the bat files.

**Comment by Brodieman** [comment]
Sounds good thanks!
