### ISSUE TITLE
Error code 0x8030002F when trying to Upgrade from Win 10

### ISSUE THREAD

**Issue by hheunis** [ntdevlabs/tiny11builder#104]
When trying to Upgrade from Win 10 to Tiny 11 I'm getting Error code 0x8030002F which indicate that the Flag 9 is not set, and I need to reconfigure the boot.wim file because it cannot create the temporary install folder.

I used Rufus to burn ISO onto a USB and copied the ISO and mounted it.

I think it has something to do with the sources folders needed for the upgrade.

Tried it on several different PCs with Win 10 22H2 and it gives the same error.

How do I reconfigure my boot.wim file to use the flag 9 settings for the first image when upgrading from Win 10 22H2 64 to Tiny 11?

**Comment by Electricurmom** [comment]
i have the same issue but not using a flash drive(not available) i extract and i try to run the setup and i get that same error 0x8030002F 
![image](https://github.com/ntdevlabs/tiny11builder/assets/98646359/a463805d-e6c4-42e9-b33d-6deff84d4db2)

**Comment by Borg6666** [comment]
mee2! :-/  Any suggestions in this?
