### ISSUE TITLE
Please update Script to match tiny11 23h2

### ISSUE THREAD

**Issue by m0usaa** [ntdevlabs/tiny11builder#105]
The new update of tiny 11 23h2 is very very good but i cant download the iso from ntdev archive because the internet here not better as well so may you you update the tiny11 builder script with new tweaks

**Comment by bravomail** [comment]
This script hasn't seen changes in 8 months. Try this one https://github.com/bravomail/tinier11 - it works with any build of WIndows 10 or 11.

**Comment by davidm71** [comment]
Was able to successfully process 22631 using the standard tiny11 converter and install it on my laptop.
