### ISSUE TITLE
Error Code 0x8030002F when Installing 

### ISSUE THREAD

**Issue by Electricurmom** [ntdevlabs/tiny11builder#106]
i just downloaded the iso from the official source and im trying to open the setup(no flash drive available) i get faced with error 0x8030002F 
![image](https://github.com/ntdevlabs/tiny11builder/assets/98646359/63040268-3514-4c53-ab86-a45a9ed81d41)

**Comment by Borg6666** [comment]
mee2!  :-/

**Comment by Electricurmom** [comment]
> mee2!  :-/ 
> I want to update from previous Tiny 11.
> I tried to mount the new ISO to a virtual drive (PowerISO) and tried to unpack it to a local folder - both ended in 0x8030002F

Okay so idk about flash drive installation I just did installed directly from my PC
It got fixed by restarting my PC
So try to restart then mount it

**Comment by Borg6666** [comment]
I already did several times.

Additionaly I used cmd with these commands:
>chkdsk /r , then reboot

and command:
>sfc /scannow , then reboot

After that, I started Setup from local disk again, which again ended in 0x8030002F both times.  😕

**Comment by greatquux** [comment]
same issue for me, also in #104
