### ISSUE TITLE
No bootable device found

### ISSUE THREAD

**Issue by NoahConstrictr** [ntdevlabs/tiny11builder#111]
I tried installing tiny11 on an nvme for my laptop (Dell latitude 7420) but kept getting missing driver issues when booting from a micro SD card with the iso flashed to it. So I put the nvme I to by desktop, got the iso again, then mounted it with file explorer and ran setup.exe to install it on the nvme without errors. I was able to boot into the nvme on my desktop, but on my laptop it doesn't even recognize it as a boot drive. In the bios, I do see the drive and it's files though. Any ideas?

**Comment by KarthikeyaThotak** [comment]
I think you should install Windows 11 on the microSD card first then run the scripts for tiny11 to trim down the requirements.
