### ISSUE TITLE
Bypasses vs. Minimal System requirement ?

### ISSUE THREAD

**Issue by liar666** [ntdevlabs/tiny11builder#114]
Hello,

I'm trying to install Tiny11 in VBox.

If I do not set at lest 2 CPUs and 8Gb of RAM, then I get the message "This PC cannot run Windows 11" (or something like that).
I've checked that the registry contains all the `ByPass*` entries, so I'm not sure where this blockage comes from.

I can install the latest "Full" Win11 iso with 1CPU/4Gb (even 2Gb) in VBox...

**Comment by daboynb** [comment]
I made a script based on this awesome project that supports full requirements bypass.

https://github.com/daboynb/windows_scripts/tree/main/windows_custom_iso_maker
