### ISSUE TITLE
Comment, No Issue

### ISSUE THREAD

**Issue by LoudMouthJester** [ntdevlabs/tiny11builder#118]
You should most definitely develop your own OS. Imagine putting 400 hours into your own creation instead of wasting your time with MS. You're being held back using that garbage. Linux has so many more possibilities. Just sayin brother... I see potential going to waste. Unleash  your skills. 

I'd more than gladly test your OS on my Nitro 5

**Comment by spftware** [comment]
> You should most definitely develop your own OS. Imagine putting 400 hours into your own creation instead of wasting your time with MS. You're being held back using that garbage. Linux has so many more possibilities. Just sayin brother... I see potential going to waste. Unleash your skills.
> 
> I'd more than gladly test your OS on my Nitro 5

You can’t just ‘create’ a new operating system.

Don’t get me wrong, Linux is great and all (for certain things), but some things are easier said than done.

You imply for NTDev to create a new OS, perhaps a fork of *nix, saying scripts for users to create a custom “debloated” version of Windows is a waste of skills?

WINE rant: *nix (Linux) can’t run Windows programs, WINE has limitations and can’t do everything. I find myself falling back to a VM. The procedure of installing it to a VM is just as easy as a regular installation.

Purpose of commenting: this script is **for Windows users**.

**Comment by iProgramMC** [comment]
> You can’t just ‘create’ a new operating system.

Absolutely you can and there is a community for that.  The internet is a wonderful place!  Although it's really hard to get your hobbyist OS to daily driver status - only one person has successfully pulled it off as far as I know, and that's Linus Torvalds.

I disagree that optimizing Windows is a waste of time, but really we shouldn't need to be in this position.
