### ISSUE TITLE
Tiny11 23H2 22621.2283? Isnt that 22H2?

### ISSUE THREAD

**Issue by davidm71** [ntdevlabs/tiny11builder#120]
Downloaded Tiny11 x64 iso and it seems like its 22621.2283 which is 22h2? Also just downloaded full 23H2  22631 from UUP and not sure if Tiny11 builder will work on it or which option to choose?

Thanks

**Comment by crborga** [comment]
This project is currently outdated. Another user has recommended this which is very similar.
https://github.com/ntdevlabs/tiny11builder/issues/105#issuecomment-1773937431
