### ISSUE TITLE
missing winre.wim

### ISSUE THREAD

**Issue by Crode123** [ntdevlabs/tiny11builder#121]
installing tiny11 2311 as an update to previous version I keep hitting a point where it seems it cannot find winre.wim inside the Install.esd archive.  I have been attempting to put a copies of winre.wim in different locations during install it still cannot find it.

```
Error                 SP         CExtractFilesFromWIM::DoExecute: Cannot extract file \Windows\System32\Recovery\winre.wim from C:\tiny11 2311 x64\Sources\Install.esd. Error 0x80070003[gle=0x00000003]
Error                 SP     Operation failed: Extract files from WIM file PathForNewOSFile, index 1 to C:\$WINDOWS.~BT\Sources\SafeOS. Error: 0x80070003[gle=0x000000b7]
Error                 SP     ExecuteOperations: Main operation execution failed. Error: 0x80070003
Error                 SP     ExecuteOperations: Failed execution phase Downlevel. Error: 0x80070003
```

**Comment by RSA99** [comment]
I have exactly the same problem.
The Error: 0x80070003 indicates a corrupted media (Install.esd?) but, as far as I can see Tiny11 Install.esd doesn't contain a WinRE.wim???
The only other explaination I can think of is that the existing Recovery setup (ReAgent.xml?) is corrupt (which I still need to check).
