### ISSUE TITLE
tiny11builder is crashing

### ISSUE THREAD

**Issue by IMTHECOOLEST** [ntdevlabs/tiny11builder#123]
i am trying to use it but when i type the the drive its in and click enter, it crashes

**Comment by jonahtylerb** [comment]
I had the same issue, but it was fixed when I mounted the iso.
After you download the iso I moved it to my thumb drive then right clicked it and hit mount. Windows will then take forever to mount it but once it mounts you should see another drive pop up. Mine was a DVD drive with a new drive letter: E. Put that new letter into the script and it should work.

**Comment by IMTHECOOLEST** [comment]
i used windows explorer
and i didn't see a mount option

**Comment by IMTHECOOLEST** [comment]
it says cant find windows then i dont know whats the rest

**Comment by IMTHECOOLEST** [comment]
fixed it, just use the uup dump version
