### ISSUE TITLE
REAGENTC.EXE: The target Windows installation was not found.

### ISSUE THREAD

**Issue by trueboroda** [ntdevlabs/tiny11builder#126]
When i run cmd `reagentc /info` i recieve this message. 
REAGENTC.EXE: The target Windows installation was not found.
![image](https://github.com/ntdevlabs/tiny11builder/assets/13153256/28340447-5a5c-409c-91db-0b06b8fb9293)
![image](https://github.com/ntdevlabs/tiny11builder/assets/13153256/f2912051-06fc-44a0-90f1-115d7e2abd0a)

Expected answer from the command: 
state of winRE: disabled or enabled. 

If target system does not set via `/target` the command should use current running system.  
![image](https://github.com/ntdevlabs/tiny11builder/assets/13153256/d8b77366-74c9-426b-9721-25e62a5d1629)

I`ve found this issue trying to create partition with Windows RE. 
https://www.tenforums.com/general-support/172567-how-recreate-windows-recovery-partition-3.html

It was checked by two clear installations of tyni11 2311 on two different machines. 

Issues is not critical. 
As workaround i use distribution disk of Tiny11 with WinRE and enable F8 boot legacy menu.
bcdedit /set {current} bootmenupolicy Legacy
https://www.tenforums.com/tutorials/22455-enable-disable-f8-advanced-boot-options-windows-10-a.html

Thank you for Tiny! It is clear perfect!

**Comment by trueboroda** [comment]
Also BCD storage has bad record for WinRE partiotion. 
![image](https://github.com/ntdevlabs/tiny11builder/assets/13153256/0527a1f8-1548-4bd1-a2df-b61674302575)

**Comment by Badmaneers** [comment]
The tiny11 23h2 is missing the Windows Re file .Here this is the missing Windows Re file .
https://drive.google.com/file/d/1sTb4rvrJnDx2sx1Hxo7u7H2rIZmeVrCv/view?usp=drivesdk

Copy it to C drive Windows/System32/Recovery/

And perform regentc /enable after copying.
