### ISSUE TITLE
Powershell closes

### ISSUE THREAD

**Issue by VariousGames** [ntdevlabs/tiny11builder#137]
dear reader
when i click the right file
Powershell opens but closes direcly

How can i fix it?
I have tryd also with powershell 7 and the windows version.

**Comment by DeveloperAnalist** [comment]
mito bommmmmm certificado louco ein bro

**Comment by DeveloperAnalist** [comment]
no xbox como na psn rodou safe

**Comment by VariousGames** [comment]
> [DeveloperAnalist](/DeveloperAnalist)

in english please :D will be more helpfull 😄

**Comment by MrShubhSharma** [comment]
To fix the issue of PowerShell closing immediately after opening, create a simple script using Notepad. Open Notepad, paste the code `Read-Host -Prompt "Press Enter to exit"`, then save the file with a `.ps1` extension (e.g., `test.ps1`). Double-click on the script to run it. This will keep the PowerShell window open until you press Enter, allowing you to see any errors. If that doesn't work, open PowerShell as an administrator, run `Get-ExecutionPolicy` and if it returns `Restricted`, change it with `Set-ExecutionPolicy RemoteSigned`. Restart your computer and try running the script again.
