### ISSUE TITLE
What if you want to use Microsoft Account during setup? Can you simply delete the unattend file?

### ISSUE THREAD

**Issue by orzcode** [ntdevlabs/tiny11builder#138]
Some people prefer a MS account during setup, rather than adding one later.

Can this be achieved by simply deleting the relevant autounattend.xml file or will that cause errors for Tiny11??

Thanks

**Comment by ntdevlabs** [comment]
Yes, you can just delete the unattended file, or you can sign in with the Microsoft Account after the installation is complete.
