### ISSUE TITLE
Windows installer error regarding unattend.xml

### ISSUE THREAD

**Issue by vtach3743** [ntdevlabs/tiny11builder#154]
I confirmed the unattend.xml is in the ISO, but when I boot to the ISO I get the following error:

Windows Setup encountered an internal error  while loading or searching for an unattend answer file. It won't let me continue. I re-downloaded the xml just to make sure the file wasn't corrupted when I originally downloaded it. Same issue.

**Comment by Promise204** [comment]
Try to double-check that the unattend.xml file is correctly formatted and doesn't contain any syntax errors.

**Comment by vtach3743** [comment]
I just downloaded the one on the site and used it as downloaded.

**Comment by smed79** [comment]
Try again with this online tool https://schneegans.de/windows/unattend-generator/
