### ISSUE TITLE
Tried Tiny11 PS and it errors out

### ISSUE THREAD

**Issue by ArDrakho** [ntdevlabs/tiny11builder#155]
I wish there was a step-by-step instructions (with visuals). The instructions in the readme file are generic.

When I tried to create the tiny11.iso...see what I saw:

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> cd C:\Users\A\Downloads\Tiny11
PS C:\Users\A\Downloads\Tiny11> ls

    Directory: C:\Users\A\Downloads\Tiny11

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         4/25/2024  10:37 PM     157911 autounattend.xml
-a---         4/25/2024  10:37 PM     150322 oscdimg.exe
-a---         4/25/2024  10:37 PM     157026 README.md
-a---         4/25/2024  10:37 PM     250612 tiny11maker.ps1
-a---         4/25/2024  10:58 PM 6812706816 Win11_23H2_English_x64v2.iso

PS C:\Users\A\Downloads\Tiny11> Set-ExecutionPolicy unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y

PS C:\Users\A\Downloads\Tiny11> ./tiny11maker.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\A\Downloads\Tiny11\tiny11maker.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:41 char:60
+   <script type="application/json" id="client-env">{"locale":"en","featureFlags": ...
+                                                            ~~~~~
Unexpected token ':"en"' in expression or statement.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:41 char:65
+   <script type="application/json" id="client-env">{"locale":"en","featureFlags": ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:41 char:542
+ ... _child_patch"]}</script>
+                    ~
The '<' operator is reserved for future use.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:240 char:84
+ ... dData">{"props":{"docsUrl":"https://docs.github.com/get-started/accessibility/ke ...
+                    ~
Unexpected token ':' in expression or statement.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:240 char:95
+ ... ops":{"docsUrl":"https://docs.github.com/get-started/accessibility/keyboard-shor ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ':"https://docs.github.com/get-started/accessibility/keyboard-shortcuts"' in expression or statement.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:240 char:168
+ ... rd-shortcuts"}}</script>
+                    ~
The '<' operator is reserved for future use.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:279 char:205
+ ... inherit p-1">  <span class="Button-content">
+                    ~
The '<' operator is reserved for future use.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:302 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:500 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\A\Downloads\Tiny11\tiny11maker.ps1:575 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Users\A\Downloads\Tiny11>

So I quit at this point. Any idea what is wrong?

Thank you!

**Comment by searinminecraft** [comment]
you may have tried to download the github page. you should click on the "Download ZIP" button here (for beginners) or clone the repo using Git (for people experienced with it)

![Screenshot_20240428-112840](https://github.com/ntdevlabs/tiny11builder/assets/114207889/f6bf9c9e-607a-4ed0-b572-5bc09b2c530f)

**Comment by ArDrakho** [comment]
OK...guess the "Save link as ..." does not work on GITHub. I will try your first suggestion since I am not a programmer.

After reading the comments about the Microsoft release of the MS-DOS 4.x source code--I now understand what they are talking about after reading your comment.
