### ISSUE TITLE
tiny11 creator 22621.525.bat shuts down your computer after copying the mounterd ISO

### ISSUE THREAD

**Issue by ruslankiskinov** [ntdevlabs/tiny11builder#16]
I used the tiny11 creator 22621.525.bat to make the build using the ISO from the Microsoft website Win11_22H2_English_x64v1.iso
which is 22621.525 build.

The machine SHUTS DOWN after the script copies the mounted ISO's contents???
To be able to continue with the build process I have to edit the bat file to start the process from line 32 (echo Getting image information:)
After that, the script created the desired ISO.

**Comment by ntdevlabs** [comment]
Well that's certainly weird...

**Comment by Katerang31** [comment]
I found the problem...

20   if not exist "%DriveLetter%\sources\install.wim" (

it should be install.esd

**Comment by Katerang31** [comment]
and 

line 33 dism /Get-WimInfo /wimfile:c:\tiny11\sources\install.wim

it should be install.esd

**Comment by Katerang31** [comment]
Replace every install.wim to install.esd ( some install2.esd )

line 20
33
40
181
182
183

**Comment by panreyes** [comment]
I would replace install.esd mentions for a variable %TINY11INSTALL_IMAGE%
And near the start of the script:
```if exist x:\sources\install.wim (
    set TINY11INSTALL_IMAGE=x:\sources\install.wim
) else (
    set TINY11INSTALL_IMAGE=x:\sources\install.esd
)```
