### ISSUE TITLE
Script quits with error because Install.wim not found in /sources folder 

### ISSUE THREAD

**Issue by elasticskyx** [ntdevlabs/tiny11builder#18]
Issue description
-----------------
The script "tiny11 creator 22621.525.bat" exits with error when using ISO downloaded from Microsoft website.
Root cause:
There is no install.wim file found in the \sources folder. 
ESD is the compressed format and must be converted to install.wim before the script can execute.
Windows 11 ISO file downloaded from website - "https://www.microsoft.com/software-download/windows11" on 05 March 2023.
Windows 11 ISO build is 10.0.22621.525

Log
---
Please enter the drive letter for the Windows 11 image: E

Can't find Windows OS Installation files in the specified Drive Letter..

Please enter the correct DVD Drive Letter..
The system cannot find the batch label specified - Stop

D:\Downloads\tiny11builder>

Resolution
---
Convert the Install.esd format to Install.wim by running the additional command:

`Dism /Export-image /SourceImageFile:c:\tiny11\sources\install.esd /SourceIndex:1 /DestinationImageFile:c:\tiny11\sources\install.wim /Compress:max /CheckIntegrity`

**Comment by ceebu** [comment]
For additional clarity:

I had to first "extract" the install.esd file to a local folder and then run the command provided by @elasticskyx  in the previous post. 

(In my case it was Dism /Export-image /SourceImageFile:C:\****\install.esd /SourceIndex:1 /DestinationImageFile:C:\****\install.wim /Compress:max /CheckIntegrity)

After extracting, we need to replace the install.esd with the newly generated install.wim. I used Anyburn for this (It allows to replace contents of the ISO without having to extract separately and rebuilding the ISO)

Once you have updated the ISO then the script executes successfully.

Thanks to @elasticskyx for the fix and @ntdevlabs  for the 'Tiny' lease of life to old hw :-)

**Comment by elasticskyx** [comment]
### Pull Request created with script changes to handle Install.esd file
The "tiny11 creator 22621.525.bat" script has been modified to convert Install.esd to Install.wim and create the modified ISO file.
**Unit Test Result: Passed**

You can get the updated script from this repo in case the pull request is not merged
[https://github.com/elasticskyx/tiny11builder/blob/convert-esd-to-wim/tiny11%20creator%2022621.525.bat](url)
