### ISSUE TITLE
PowerShell DISM cmdlets only work on Insider builds

### ISSUE THREAD

**Issue by dekart811** [ntdevlabs/tiny11builder#181]
This should be reverted, because `-StartComponentCleanup` for `Repair-WindowsImage` doesn't exist in *Windows 10 22H2* or *Windows 11 23H2*. So `Repair-WindowsImage -Path "$mainOSDrive\scratchdir" -StartComponentCleanup -ResetBase` will **always** fail.
So the only way to build this right now properly is by using an *Windows 11* insider build, which isn't a good idea IMO.

_Originally posted by @dekart811 in https://github.com/ntdevlabs/tiny11builder/issues/173#issuecomment-2099044519_

**Comment by dekart811** [comment]
Fixed in https://github.com/ntdevlabs/tiny11builder/pull/182

**Comment by Cris70** [comment]
I downloaded Tiny11 november 2024 edition, but I still have errors on Windows 10 22H2:
`Repair-WindowsImage : Impossibile trovare un parametro corrispondente al nome 'StartComponentCleanup'.`
Sorry, it's Italian, but the meaning should be clear: it cannot find the 'StartComponentCleanup' parameter.

**Comment by FREEWING-JP** [comment]
> downloaded Tiny11 november 2024 edition, but I still have errors on Windows 10 22H2:

The current version has been reinstated in this commit .
So the same problem occurs on Windows 10 22H2 .
https://github.com/ntdevlabs/tiny11builder/commit/bba078c34bd2108188a09653ea1de32edffe7a93
