### ISSUE TITLE
Disable BitLocker's automatic device encryption by default

### ISSUE THREAD

**Issue by Kichura** [ntdevlabs/tiny11builder#184]
When installing Windows 11's latest 24H2 build, The device encryption is automatically set to enabled upon installing and while this can be good for specific security scenarios - In reality, this can in turn cause problems in how users might handle the recovery key or lose access to their Microsoft account as both can prove fatal if the PC was ever encrypted with this feature. *(but also causes other problems along the way such as PC being too old to support it or the repair shop gets stuck fixing your pc for example)*

To prevent this feature from being automatically enabled, Add the following script line to the powershell script while the Windows setup's SYSTEM registry hive is mounted:

`& 'reg' 'add' 'HKLM\zSYSTEM\ControlSet001\Control\BitLocker' '/v' 'PreventDeviceEncryption' '/t' 'REG_DWORD' '/d' '1' '/f' >null`

**Comment by MetzgerGeorg** [comment]
VERY GOOD point!!
