### ISSUE TITLE
Script completes with to errors and no iso file

### ISSUE THREAD

**Issue by LUGen333** [ntdevlabs/tiny11builder#19]
the tiny11 image is now completed. Proceeding with the making of the ISO...
Copying unattended file for bypassing MS account on OOBE...
The system cannot find the file specified.

Creating ISO image...
'C:\Users\username\Desktop\New' is not recognized as an internal or external command,
operable program or batch file.
Creation completed Press any key to exit the script...
Press any key to continue . . .

No iso file in folder with bat file

**Comment by AKGamerTech** [comment]
this happens with folders that contain spaces in the name 
(for the devs) the easiest solution is adding "" where the name of the folder is defined in the script 
(for normal users) use a folder without spaces

and don't forget to run as admin

**Comment by dfhbsdtfb54y** [comment]
hello I got this problem to is there is a video that got that similar issue/

**Comment by AKGamerTech** [comment]
> hello I got this problem to is there is a video that got that similar issue/ 

A video? Like a video on how to do that correctly?
