### ISSUE TITLE
what happens if you use windows 10

### ISSUE THREAD

**Issue by piotr25691** [ntdevlabs/tiny11builder#2]
What will happen if you feed this tool a Windows 10 image? I would've treated my ISO of Windows 10 S 1709 with this, but it's probably not going to work.

**Comment by UnidentifiedTag** [comment]
You'll end up with script errors during removal of some apps as the names won't match up, along with invalid and unnecessary registry changes. Obviously this is meant for Windows 11 not 10, hence the name Tiny11

I'm sure @ntdevlabs agrees with my assessment ?

**Comment by piotr25691** [comment]
> You'll end up with script errors during removal of some apps as the names won't match up, along with invalid and unnecessary registry changes. Obviously this is meant for Windows 11 not 10, hence the name Tiny11
> 
> I'm sure @ntdevlabs agrees with my assessment ?

I can always fork this project and change the package names appropriately

**Comment by tutacat** [comment]
> 

Just use tiny10...

**Comment by piotr25691** [comment]
> > 
> 
> Just use tiny10...

no 64 bit tiny10 can be acquired anymore, except old versions
