### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by coopeeo** [ntdevlabs/tiny11builder#205]
What's the difference between tiny11maker.ps1 and tiny11Coremaker.ps1?

**Comment by freckhard** [comment]
Hey @coopeeo, it says it clearly on the README.md, have a look:

> For tiny11 core:

it removes all of the above (as from tiny11maker) plus

>   all of the above +
    Windows Component Store (WinSxS)
    Windows Defender (only disabled, can be enabled back if needed)
    Windows Update (Windows Update wouldn't work anyway without WinSxS, so enabling it would only put the system in a state where it would try to update but fail spectacularily)
    WinRE
>
>Keep in mind that **you cannot add back features in tiny11 core**! 

You're welcome!

**Comment by coopeeo** [comment]
Okay, some parts weee confusing me on that but thanks for the clarification!
