### ISSUE TITLE
Windows update not working

### ISSUE THREAD

**Issue by Batuhan445** [ntdevlabs/tiny11builder#22]
all tryed normal solutions : 

- sfc /scannow
- windows update fix tool
- dism /online /cleanup-image /startcomponentcleanup

and more... but not working

**Comment by Batuhan445** [comment]
error code : 0x80070002

**Comment by clorophilla** [comment]
It's working fine here, did you do anything to your install (add programs, change settings...)?

**Comment by Batuhan445** [comment]
No

**Comment by ianis58** [comment]
It's not the same error code, but I fixed my issues with windows update on a tiny11 system with the following commands:
[https://answers.microsoft.com/en-us/windows/forum/all/windows-11-update-download-error-0x80248007/19a57def-3f92-4512-842d-ce5c7b736ea4](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-update-download-error-0x80248007/19a57def-3f92-4512-842d-ce5c7b736ea4)

For backup I copy the commands here:

net stop wuauserv
net stop cryptSvc
net stop bits
net stop msiserver
ren C:\Windows\SoftwareDistribution SoftwareDistribution.old
ren C:\Windows\System32\catroot2 catroot2.old
net start wuauserv
net start cryptSvc
net start bits
net start msiserver
