### ISSUE TITLE
Some issues I found while testing.

### ISSUE THREAD

**Issue by clorophilla** [ntdevlabs/tiny11builder#23]
Before anything, thank you! I'm really satisfied with your work here.

While I used Tiny11, I found some stuff that doesn't work as expected:
- Changing Windows language to anything other than English breaks some program windows. If you try opening the settings for programs like HWiNFO, MSI Afterburner or 7-Zip, nothing happens. Not even a blink. Changing the language back solves this.

- I use an Xbox One wireless controller with my PC and its Guide button doesn't work at all. I guess it's because of the Xbox programs that got removed. I'll try restoring them.

**Comment by clorophilla** [comment]
I tried the script with a Brazilian Portuguese official ISO file and can confirm that i didn't have the first issue I reported. For the Guide button you need the package "XboxGamingOverlay" (solves when I leave it out of the script removal).

Still, the process of making the ISO from the script didn't go smoothly, as some packages either aren't present of the image or get installed after Windows activation (Cortana's package is "Microsoft.549981C3F5F10_3.2204.14815.0_neutral_~_8wekyb3d8bbwe" on my 22621.525 ISO, Teams and Family are not present). There should be a way of selecting a package to remove even when the version/build don't match.

I attached a text file with what happened.
[tiny11 creator 22621.525.log](https://github.com/ntdevlabs/tiny11builder/files/10938280/tiny11.creator.22621.525.log)

**Comment by foltz61** [comment]
While trying to install I get a notification that my computer isn't supported. It's as if the hardware requirement isn't being removed by the script.
