### ISSUE TITLE
Tiny Win 11 of new images

### ISSUE THREAD

**Issue by WestDvina** [ntdevlabs/tiny11builder#25]
Thanks for the constructor. Everything works perfectly!
How to make a tiny Win 11 from new images v. 25309, v. 25314 and later?

**Comment by ianis58** [comment]
Hi,
You can use the forked version from this tool in my repositories: ianis58/tiny11builder .
It's the same script, but done in PowerShell, and does not depend on some specific build number to work.
It also have additional tweaks like dark theme enabled by default and some file explorer config turned on (show hidden files, show known file extensions, ...).
