### ISSUE TITLE
Not getting an ISO file after running the script.

### ISSUE THREAD

**Issue by P1NBA11ER** [ntdevlabs/tiny11builder#26]
Looking at the instructions, which seem simple enough, I'm having a problem getting from step 6 to step 7. Is there a step that should be there that I'm missing or is there an error in the script that's causing me not to get an ISO file out. What I do get it a "Tiny 11" folder on my C drive but that's it and obviously, that's not an ISO file that I can turn into a bootable drive.

**Comment by P1NBA11ER** [comment]
Yes, there is a step missing. One must tell the script when prompted a name(?) for the ISO file that will be created. The prompt is non-intuitive in it's description of what it would like one to do at this point. This should be noted in the readme or the instructions as a step that must be completed in order for the ISO to be created.

**Comment by BeanBagKing** [comment]
In case anyone else comes across this, I think the description could be more clear. However, the index number is listed above that statement. You can see a screenshot of it and an example here: https://www.tomshardware.com/how-to/make-lightweight-windows-11-image-tiny11-builder

> 
> Depending on whether your ISO file contains just one version of Windows 11 or many, you may see a list of different Windows “images,” including Windows 11 Home, Windows 11 Pro and Windows 11 Pro Education. 
> 
> 8. Enter the image number for the Windows version you want and hit Enter. In our case, we hit “1” for Windows 11 Home. If there are no images listed, choose 1 for the default.

**Comment by NoahConstrictr** [comment]
I had this issue. If you haven't already tried, make sure there's no spaces in the file path where you extracted the bat files to. For example this would not work:
'C:\Users\John Doe'
But this would:
'C:\Users\JohnDoe'
What I did was just extract it to the root C drive.
