### ISSUE TITLE
ISO file boots but gives an isntall.wim missing error

### ISSUE THREAD

**Issue by P1NBA11ER** [ntdevlabs/tiny11builder#27]
I can boot from the ISO created with the tool but I get an error ( I assume when the installer launches) that the install.wim is missing, and the computer than restarts automatically.

**Comment by P1NBA11ER** [comment]
Doing some more digging and it looks like isntall.wim is not being copied to the thumb drive due to an error that the file is "too large for the destination file system."

**Comment by P1NBA11ER** [comment]
So the problem with this is the DOS window scrolls the options for the Windows installer version that need to be selected outside of the viewport. Surely I'm not the only one that is going to have this problem. The script should be updated to indicate the exact step that needs to occur and not simply say "please enter the image index" when the image index may not even be visible on screen. I would suggest something like "please enter the image index for the Windows version you wish to create (may need to scroll up for all versions)"

**Comment by ianis58** [comment]
Hi,
You can use the forked version from this tool in my repositories: ianis58/tiny11builder .
It's the same script, but done in PowerShell.
It does not ask for a drive letter, because it manage it itself.
