### ISSUE TITLE
Failed cleanup of scratchdir, unable to delete directory

### ISSUE THREAD

**Issue by jerudamaja** [ntdevlabs/tiny11builder#28]
c:\scratchdir\.... - Access is denied.

**Comment by cristianmoroaica** [comment]
Had the same issue. On Windows:
Run powershell/terminal as admin, then:

takeown /F "C:\scratchdir" /R /A

icacls "C:\scratchdir" /grant Administrators:F /T

Remove-Item -Path "C:\scratchdir" -Recurse -Force

Worked for me.

**Comment by ssmsa** [comment]
> Had the same issue. On Windows: Run powershell/terminal as admin, then:
> 
> takeown /F "C:\scratchdir" /R /A
> 
> icacls "C:\scratchdir" /grant Administrators:F /T
> 
> Remove-Item -Path "C:\scratchdir" -Recurse -Force
> 
> Worked for me.

Thanks very much

**Comment by Ashetf2** [comment]
I tried this but for some reason I don't have access to the files even when giving admin permissions

**Comment by WifiFishy** [comment]
I have also tried the same commands from @cristianmoroaica and I'm still getting "Access to the path is denied" errors.

**Comment by WuslCorp** [comment]
try
dism /unmount-image /mountdir:c:\scratchdir /discard

**Comment by SkyExploreWasTaken** [comment]
> try dism /unmount-image /mountdir:c:\scratchdir /discard

It worked for me, thank you !
