### ISSUE TITLE
Asks for Drive Letter Then Instantly Closes the Window.

### ISSUE THREAD

**Issue by RetroSwamp** [ntdevlabs/tiny11builder#29]
I feel mad stupid but got everything downloaded and ready to go and when I ran the proper bat the CMD window opens up flawlessly and asks for the drive letter for the ISO which is mounted then instantly the CMD window closed with no log or error.

**Comment by ohmmee** [comment]
in reference to https://www.tomshardware.com/how-to/make-lightweight-windows-11-image-tiny11-builder

_The reason you might have to try both is that the information is stored either in a file called install.wim or install.esd. In my case, install.wim worked with an ISO I had downloaded directly from Microsoft while install.esd worked when I used the Media Creation Tool to build my ISO._

open the specified Batch file (.bat) in text editor and replace all install.wim to install.esd
then start running the batch file with administrator previlieges.

**Comment by green-potat** [comment]
Thanks ohmmee, that actually worked for me!
