### ISSUE TITLE
Is there a way to migrate current installation to tiny 11 build?

### ISSUE THREAD

**Issue by i-am-R00k** [ntdevlabs/tiny11builder#30]
Let's say you don't want to reinstall every app and games you already have in your system drive as well as your other drives. Is there a way to reinstall your windows 11 installation with a tiny 11 build without having to delete these files and software?

**Comment by 0n1cOn3** [comment]
After creating the ISO, have you tried mounting it and running the installer for the upgrade?
Test this in a virtual machine before running it on a production machine.
