### ISSUE TITLE
please support version 10.0.22621.1105

### ISSUE THREAD

**Issue by sfareg** [ntdevlabs/tiny11builder#31]
please support the last version Windows 11  build 10.0.22621.1105

**Comment by ianis58** [comment]
Hi,
You can use the forked version from this tool in my repositories: ianis58/tiny11builder .
It's the same script, but done in PowerShell, and does not depend on some specific build number or app versions to work.
It also have additional tweaks like dark theme enabled by default and some file explorer config turned on (show hidden files, show known file extensions, ...).

**Comment by sfareg** [comment]
i used this tools but show errors

[tiny11.log](https://github.com/ntdevlabs/tiny11builder/files/15234505/tiny11.log)
