### ISSUE TITLE
Local Security Authority protection is disabled

### ISSUE THREAD

**Issue by csolisr** [ntdevlabs/tiny11builder#33]
Local Security Authority (LSA) protection is a mechanism that prevents unsigned drivers and addons to be loaded on the local security authority. Windows Security is currently complaining of this issue in both of my Tiny11 computers, and enabling it and rebooting still does not clear the warning.

**Comment by ianis58** [comment]
Hi @csolisr 
Can you share a screenshot of it?
Do you have any clue what removal might disable it?

Thanks

**Comment by ianis58** [comment]
Hi @csolisr 
Can you share a screenshot of it?
Do you have any clue what removal might disable it?

Thanks

Edit:
@csolisr 
Read this 
https://www.bleepingcomputer.com/news/microsoft/microsoft-defender-update-behind-windows-lsa-protection-warnings/

**Comment by csolisr** [comment]
Thanks for letting me know that the issue lays on Microsoft and not the Tiny11 tool.

**Comment by ianis58** [comment]
Yeah I was kind of scared too, 'cause I'm running it on my main desktop.
