### ISSUE TITLE
Completely Bare Bones preset?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [ntdevlabs/tiny11builder#40]
How can we go about getting a build that has just start menu, settings, explorer, and the ability to install Appx, and msu? Ie the image should be manually serviceable, no wsus, no store, no apps, etc.

**Comment by suchislife801** [comment]
A bare bones version of Windows 11 would be like a gift to the world.

**Comment by BiatuAutMiahn** [comment]
So why was this marked as completed when we don't have any options for a bare bones build like I mentioned in my OP?
