### ISSUE TITLE
IIS not available in Optional Features

### ISSUE THREAD

**Issue by jp06** [ntdevlabs/tiny11builder#45]
I am trying out the ARM64 build as a VM with my Macbook Air M1. Just noticed that the IIS feature is missing. Anyone knows how to restore it when the custom build is already installed? Or at least, if someone can point out what to change in the script to avoid removing IIS, that would be great. Thanks in advance!

**Comment by ianis58** [comment]
Does IIS for arm exists?

**Comment by jp06** [comment]
I tried mounting an ARM build downloaded/generated with UUP dump script. `Get-WindowsOptionalFeature` does list the IIS modules in it, whereas the Tiny11 doesn't have it. I haven't actually tried though as I am not able to install that build in my VM.
