### ISSUE TITLE
Is this project abandonded yet?

### ISSUE THREAD

**Issue by StenApp** [ntdevlabs/tiny11builder#46]
This project has potential,
unfortunately the creator has abandoned it...

**Comment by ianis58** [comment]
Feel free to join me on my forked version, with many enhancements already.
Let me know if you have ideas, also please do pull requests if you're able to improve stuff :)
Just check the tiny11builder fork in my repos: ianis58/tiny11builder

**Comment by Karl-WE** [comment]
Do you tend to follow up open PR here and forge them into your repo and document them?

**Comment by StenApp** [comment]
No, i like if cool ideas don‘t end in an digital graveyard after showing something great
