### ISSUE TITLE
Windows Search Bar not Working at all

### ISSUE THREAD

**Issue by Dylanchill** [ntdevlabs/tiny11builder#49]
Essentially the title. Whether I use the magnifying glass bar, or the windows bar, I can not search for any programs whatsoever. I'll attach a small video demonstrating what I mean [here](https://imgur.com/a/sWo5hSg).

If anyone knows why this is happening (probably me being dumb), I'd really appreciate it!

**Comment by dennyamarojr** [comment]
Hi @Dylanchill 

First you only tell the problem, but you didn't mention the build of windows 11 you're using, which tiny builder you use and if you make changes to the tiny builder. Please provide more information, so we can understand what is happening and better assist you.

**Comment by Dylanchill** [comment]
Hi @dennyamarojr!

I'm not too sure on all fronts I'll be honest, but after doing some research I think I've found the issue, I'm just unsure on how to resolve it.

I believe when Tiny11 Builder was being set up (I did not change anything, just installed like normal), whatever windows module(?) makes the Search Bar function (for example Bing, or Edge given when you search something it gives you web results from Bing or Edge) is missing, I just have no idea how to get it back.

I formatted the USB to be used for other things after I used it to install Tiny11 so the install files themselves are gone.

If you have any idea what may be causing this then please let me know.

Thanks so much!
