### ISSUE TITLE
Add Narrator and Microsoft TTS

### ISSUE THREAD

**Issue by Mudb0y** [ntdevlabs/tiny11builder#55]
I don't think these 2 things cause huge issues at least in terms of telemetry, and to my knowledge they're not super big either so they shouldn't cause a dramatic increase of disk space usage.
I'm blind and would love to try out the Tiny Windows versions on some of my hardware, but the unavailability of Narrator makes it that much harder, given there's no speech in the installer and the installed system in that case.

**Comment by Mudb0y** [comment]
@ntdevlabs I've attempted installing Tiny10 on my HP Mini-110 netbook. Narrator works during initial setup, however it doesn't work after installation. Scanning the screen with my phone confirmed Narrator starts, however lack of TTS for EN-US prevents it from speaking.
I haven't tested with Tiny-11 yet, however given both have TTS removed I presume the issue will be prevalent there as well.
I'd appreciate it if you could test on a functional Tiny10 / Tiny11 install by starting Narrator, either by pressing WIN+CTRL+enter or starting it from the accessibility screen.
If you need any more assistance or something, let me know and we can take this discussion outside of GH as to not clutter the issues if need be.

**Comment by rkingett** [comment]
I just tried the latest Tiny 11, I think, 2303, and it appears as though Narrator and TTS function have been disabled. The beta, 2202, has these features. Is there a latest distro with narrator? I tried it on a virtual machine.
