### ISSUE TITLE
No install.wim

### ISSUE THREAD

**Issue by radiabyte** [ntdevlabs/tiny11builder#57]
So the previous day I downloaded windows 11 version 22621.525 but the problem is there is no install.wim instead there is install.esd
so I replaces the install.wim(s) in batch code into install.esd but when I ran the code dism couldn't access the image

**Comment by ianis58** [comment]
Hi, where do you download the iso from?

**Comment by rayzorben** [comment]
Downloaded the ISO off official Microsoft website for Windows 11. Verified it is 22621.525 by installing it into virtual machine and running winver. 

I also have the same issue, I can the .525 version of tiny and get the following error:

![image](https://github.com/ntdevlabs/tiny11builder/assets/7737834/5680d131-910e-4748-b897-3096d72d5aa0)

**Comment by metheowww** [comment]
i made some changes here:

...
md c:\scratchdir
dism /export-image /SourceImageFile:c:\tiny11\sources\install.esd /SourceIndex:%index% /DestinationImageFile:c:\tiny11\sources\install.wim /Compress:max /CheckIntegrity 
del c:\tiny11\sources\install.esd    
dism /mount-image /imagefile:c:\tiny11\sources\install.wim /index:%index% /mountdir:c:\scratchdir
...

save and try again.
