### ISSUE TITLE
Pleade add German and Moment 3 support

### ISSUE THREAD

**Issue by Schrotty74** [ntdevlabs/tiny11builder#58]
Please can you add fore german iso and Moment 3 Windows 11 Insider Preview 10.0.22624

**Comment by tukiyo** [comment]
Japanese iso please

**Comment by Karl-WE** [comment]
You can custom the scripts and replace en-US by your language e. g
jp-JP or de-DE.

There is a pull request that makes it more universal using the SID instead of fixed admin account names.
