### ISSUE TITLE
Boot Mgr is Missing 

### ISSUE THREAD

**Issue by armup31** [ntdevlabs/tiny11builder#60]
Hey guys i had tiny 11 installed on my hard drive along with Ubuntu, but yesterday i messed something up and now my bootmgr file is missing so i cannot boot into windows, I am seeking help about this and want someone to guide me on how can I repair it, i also have tiny 11 on my bootable usb but i am not aware how do I boot into windows recovery since there is no option like that in the windows setup, i saw couple of tutorials but there isn't a option saying "repair windows" so can you guys please help me? and btw i can boot into Ubuntu and do things.

**Comment by armup31** [comment]
nvm

**Comment by sussyboy123** [comment]
>I Know I'm Late But How?

**Comment by armup31** [comment]
> > I Know I'm Late But How?

It happened when I tried to use the window manage disk settings, look like something's wrong with it.
