### ISSUE TITLE
Is there a way to downgrade to tiny11 without uninstalling applications?

### ISSUE THREAD

**Issue by i-am-R00k** [ntdevlabs/tiny11builder#61]
I'm currently considering downgrading my os to tiny11 but there is a lot of applications installed on my laptop, most of them are games, multimedia software, and python packages for programming. Is there a way to downgrade to tiny11 without comprimising these things or is this the equivalent of reinstalling everything from scratch?

**Comment by Karl-WE** [comment]
Not that easy. If not removed in the base Image, apps are deployed per User profile.

Of course there are plenty scripts available to to remove all apps of your user.

Check out
https://github.com/builtbybel/ThisIsWin11/releases
