### ISSUE TITLE
Question - What is a SKU and do I actually need it?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ntdevlabs/tiny11builder#62]
So I saw a youtuber - I think it was DeBaur maybe? At any rate they will talking about this tool and I mostly know what I am doing but I am stuck at step SKU - please advise ...

**Comment by superpupervlad** [comment]
Here is the answer https://github.com/ntdevlabs/tiny11builder/issues/26#issuecomment-1522066110
TLDR This is the index of image that script just printed and more likely you need "1"
