### ISSUE TITLE
Change the extensions from BAT to CMD

### ISSUE THREAD

**Issue by ExtremePro11299** [ntdevlabs/tiny11builder#71]
**CMD** files are better than BAT files. [More info here](https://www.geeksforgeeks.org/difference-between-cmd-and-bat/)

**Comment by luke-beep** [comment]
You do understand that both .BAT and .CMD files use the CMD.exe command interpreter right?

**Comment by ExtremePro11299** [comment]
Yup. Except that CMD files are only compatible with cmd.exe, while BAT files are compatible with cmd.exe and [command.com](https://en.wikipedia.org/wiki/COMMAND.COM).

**Comment by ExtremePro11299** [comment]
So are you going to do it?

**Comment by thebignoob1** [comment]
useless issue.
