### ISSUE TITLE
Which script for 22621.1341?

### ISSUE THREAD

**Issue by hyacin75** [ntdevlabs/tiny11builder#73]
"Latest version from Microsoft" now seems to be 22621.1341, not the version mentioned in the README.  Do any of the scripts work for this version?  Or do we have to download an older version until a new script is developed?

**Comment by RaySlash** [comment]
The OP have already mentioned about getting the older images from UUPDump https://github.com/uup-dump-dev . You got to wait or update the existing yourself and send a PR (maybe).
