### ISSUE TITLE
the tiny11 image is now completed. Proceeding with the making of the ISO... Copying unattended file for bypassing MS account on OOBE... The system cannot find the file specified.

### ISSUE THREAD

**Issue by dfhbsdtfb54y** [ntdevlabs/tiny11builder#75]
I Follow the CyberCPU Tech Videos about this (https://youtu.be/qiF30VGfGhA) and on the part of the video (10:03) i get this:

the tiny11 image is now completed. Proceeding with the making of the ISO...
Copying unattended file for bypassing MS account on OOBE...
The system cannot find the file specified.

Creating ISO image...
'C:\Users\username\Desktop\New' is not recognized as an internal or external command,
operable program or batch file.
Creation completed Press any key to exit the script...
Press any key to continue . . .

**Comment by allover326** [comment]
Im having the exact same issue

**Comment by 0hip** [comment]
Is "tiny11builder" directory located at some path like: 'C:\Users\user name\Desktop\New folder' (look at the white spaces)?
Put the tiny11builder to a path which contains NO white spaces.
