### ISSUE TITLE
oscdimg not found

### ISSUE THREAD

**Issue by foltz61** [ntdevlabs/tiny11builder#9]
After running the tiny11 creator 22621.525.bat file an error message that oscdimg can't be found is displayed. This is on Windows 10 Home. Thanks for creating this utility.

**Comment by RobN12** [comment]
I had an issue with spaces in the path to oscdimg giving me an error message when it went to create the ISO.  I fixed it by putting double quotes around where the command is listed near the end of the script changing %~dp0oscdimg.exe to  "%~dp0oscdimg.exe" and %~dp0tiny11.iso to "%~dp0tiny11.iso".  See if this works for you.

**Comment by foltz61** [comment]
I added the program to Windows/System32 then realized it is looking for it in the same folder as the bat file. I copied it there and it's currently running again. If that happens to fail I'll try your suggestion. Thanks.

**Comment by foltz61** [comment]
Adding the program to the folder where the .bat file is ran from worked.

**Comment by foltz61** [comment]
As a heads up, the version of oscdimg available to download here wasn't compatible with my version of Windows 10. I had to revert bsck to a version I found elsewhere.

**Comment by srdgtr** [comment]
Probably because the offered version is for win32. If i install the deployment and assessment tools, i find the right exe in C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg.
