### ISSUE TITLE
tiny11.iso is not created at final stage

### ISSUE THREAD

**Issue by webdev866** [ntdevlabs/tiny11builder#91]
Hi,
This took alot of time and finally the file is not created, I get this error:

Creating ISO image...
This version of C:\Users\X\Desktop\TinyBuilder\tiny11builder-main\tiny11builder-main\oscdimg.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

I'm using Windows 10 Pro

This is the second time this happen, how to solve it?

**Comment by volodymyrzuyev** [comment]
The folder that you are storing the script in has to be without spaces in it. IE not "Tiny 11" but "Tiny11"

**Comment by McRex007** [comment]
Also happens if your account name has spaces in it. Unfortunately, that is much harder to change, since while you can change what your account name displays as, your user folder remains as it was named previously. It could probably be fixed by putting the relevant paths in quotes.
