### ISSUE TITLE
newer windows 11 releases not working

### ISSUE THREAD

**Issue by ajarcon** [ntdevlabs/tiny11builder#92]
I tried some of the newer versions and the installer says something is missing and closes or the tiny11creator.bat just spits out a error message saying to umount the image and try again i know its not ment for newer versions but cant u guys update it its been 5 months

**Comment by InputSoldatcc** [comment]
This will probably be fixed.

I think it automatically updates to the new version during Setup if you install an older version. I remember installing an old version of Win10 (i think it was like 20H1?) and it updated to 23H2.

Or you can try updating through Windows Update?

**Comment by InputSoldatcc** [comment]
"As of now, only build 22621.525 (the one that can be downloaded from the Microsoft website), 22621.1265 (the "latest" public build) and 25300 (latest Insider build as of now) are supported."

I think its best to wait for an update.

**Comment by ajarcon** [comment]
I tryed using 22621.1265 same problem

**Comment by ajarcon** [comment]
version 22621.2115 from uup dump works

**Comment by ajarcon** [comment]
nope it keeps restarting during install

**Comment by InputSoldatcc** [comment]
I think Tiny11Builder might be changing the wrong files on newer builds ISO.

**Comment by ajarcon** [comment]
oof tho i did find a tool that kinda does the same thing but more annoying to use the link https://gist.github.com/ThioJoe/5cc29231c5cb1a8f051df28a69073f77

**Comment by ajarcon** [comment]
tho somethinsg cant be removed or some breaks windows

**Comment by InputSoldatcc** [comment]
> nope it keeps restarting during install

Did you take out the USB after it the second boot?

**Comment by ajarcon** [comment]
no it stayed there

**Comment by InputSoldatcc** [comment]
You have to remove the USB after the second boot.
Or change the boot priority to the hard disk after the second boot through the BIOS.
