### ISSUE TITLE
Bat file crashes after typing the drive letter

### ISSUE THREAD

**Issue by CrocDev** [ntdevlabs/tiny11builder#95]
When i typed my drive letter on the .bat file it just crashes.
I have the windows 11 iso in a pendrive and its on the letter F, can someone fix that issue ?

**Comment by InputSoldatcc** [comment]
Did you run it as administrator?

**Comment by JCalles5** [comment]
Update: I found one issue. The bat file looks for "install.wim" and the iso now uses "install.esd". Fixing that file did not fix the script however. I continue to run into errors. If I find a solution I'll post an update.

**Comment by InputSoldatcc** [comment]
I think the script still expects Install.wim, so it functions to work with install.wim instead of install.esd for the entirety of the script.

Also, you can try moving the ISO file into the C: drive instead.

**Comment by The0fficialSharky** [comment]
> Did you run it as administrator?

Yea i did run as admin

**Comment by The0fficialSharky** [comment]
> Update: I found one issue. The bat file looks for "install.wim" and the iso now uses "install.esd". Fixing that file did not fix the script however. I continue to run into errors. If I find a solution I'll post an update.

How do i change the install.esd to install.wim ?

**Comment by InputSoldatcc** [comment]
That wont work. A full rewrite to access the install.esd is most likely required.
Install.esd is more compressed than install.wim, so its harder to manipulate.

**Comment by InputSoldatcc** [comment]
"Hence it became Large11"
