### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by FRANEKbinbanek** [ntdevlabs/tiny11builder#96]
Will be there support to make tiny11 / 10 for arm devices?

**Comment by honam18** [comment]
just download tiny11 r1 iso. it's the arm iso

**Comment by FRANEKbinbanek** [comment]
> just download tiny11 r1 iso. it's the arm iso

Yeah, but I want to customize it
Like keep edge and other stuff

**Comment by luke-beep** [comment]
Windows 11 has ARM support already. [learn.microsoft.com](https://learn.microsoft.com/en-us/windows/arm/overview)

**Comment by FRANEKbinbanek** [comment]
Okay but I want tiny 11 arm???

> Windows 11 has ARM support already. [learn.microsoft.com](https://learn.microsoft.com/en-us/windows/arm/overview)

**Comment by regs01** [comment]
I tried `tiny11a64_r1.iso` with Qemu 8.1.0 on Windows x64. But i can't get it booted.

```
./qemu-system-aarch64.exe -M virt -cpu cortex-a76 -smp 4 --accel tcg,thread=multi -m 4G -bios edk2-aarch64-code.fd -drive if=virtio,file=tiny11disk.img -cdrom tiny11a64_r1.iso -boot d -device qemu-xhci -device usb-tablet -device usb-kbd -device virtio-gpu
```

end up with a permanent logo and next lines in serial0 output
```
ConvertPages: failed to find range 10000000 - 10121FFF
ConvertPages: failed to find range 102000 - 102FFF
```

Debian ARM64 boots into graphical intaller.
