### ISSUE TITLE
Merge Tiny11 NTDEV with Tiny11 Microsoft

### ISSUE THREAD

**Issue by mohamadfg-dev** [ntdevlabs/tiny11builder#97]
Microsoft has released a much lighter version of Windows called Tiny 11, which I installed by mistake. However, in this version, all features belonging to Microsoft have been removed, such as Microsoft Store, PowerShell, printers, Windows Update, etc.  How can I merge some optional features from the Tiny11 version NTDEV into the Tiny11 version provided by Microsoft?

**Comment by bannert1337** [comment]
Microsoft didn't release Tiny11. It is a community-made custom version.
