### ISSUE TITLE
Patcher Emergency Update

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [ntdevlabs/tiny11builder#98]
Can this Tiny11 Patcher be updated to support breaking new security by insider builds and to remove ghost of Edge and Windows Security app

It would be nice to have fully working patcher that can remove that kind of bloatware completely from the system, including it's ghost (invisible icons of the removed apps)

**Comment by KonTy** [comment]
Check out new MicroWin feature in winutil https://github.com/ChrisTitusTech/winutil it can do what you are asking for amd much more
